version: 0.2

phases:
  install: 
    runtime-versions:
      java: latest
    commands:
      - sudo apt install -y apache-maven
      - sudo apt install java-1.8.0-openjdk-devel.x86_64 -y
      - sudo apt install zip -y
  build:
    commands:
      - sudo mvn clean install
artifacts:
  files:
    - target/webapp-1-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - beforeinstall.sh
    - applicationstart.sh
  discard-paths: yes
